### PR TITLE
Fix for Log4Cxx Windows Debug

### PR DESCRIPTION
**Pull request by mjcarroll**
Still WIP for CI.

Signed-off-by: Michael Carroll <michael@openrobotics.org>

### CODE REVIEW

**Comment by mjcarroll** [comment]
[Build Status](https://ci.ros2.org/job/ci_windows/6838/)

**Comment by mjcarroll** [comment]
Windows Debug to `rcl` with updated log4cxx choco packages:

[Build Status](https://ci.ros2.org/job/ci_windows/6861/)

**Review by jacobperron — DISMISSED** [review]
:tada:

**Comment by mjcarroll** [comment]
Testing a fix across platforms:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/7051/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/3283/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/5779/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/6871/)

**Comment by clalancette** [comment]
Closing this out, as we are no longer using log4cxx as out default backend implementation.

**Pull request closed without merging**
