### PR TITLE
Use rcutils_expand_user() in rcl_logging_get_logging_directory()

### PR DESCRIPTION
**Pull request by christophebedard**
Follow-up to #53, now that `rcutils_expand_user` has been added (https://github.com/ros2/rcutils/pull/298).

### CODE REVIEW

**Comment by christophebedard** [comment]
I'm guessing a new release of `rcutils` might need to be created for the Rpr job to pass.

**Comment by clalancette** [comment]
> I'm guessing a new release of `rcutils` might need to be created for the Rpr job to pass.

Agreed, I'll go ahead and do that.

**Comment by clalancette** [comment]
New release of rcutils is done, lets see if the PR build succeeds now.

**Comment by clalancette** [comment]
@ros-pull-request-builder retest this please

**Review by clalancette — APPROVED** [review]
Looks good to me now that PR jobs are passing.  I'll also do a CI run on it.

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12789/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7748/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10503/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12736/)

**Comment by clalancette** [comment]
The 4 failures on Windows are flaky right now.  So I'm going to go ahead and merge this, thanks for the change.

**Pull request merged**
