### PR TITLE
Added rcl_logging_spdlog tests

### PR DESCRIPTION
**Pull request by ahcorde**
spdlog will generate a log file inside `~/.ros/log`. The idea of this test is to write some log messages using different log levels and then review the generated file and check that the messages are written properly

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Comment by ahcorde** [comment]
Running CI up-to rcl_logging_spdlog to check the new test

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/10774/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/6165/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/8771/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/10664/)

**Comment by sloretz** [comment]
@ahcorde friendly ping, is this PR ready for review?

**Comment by ahcorde** [comment]
Yes, this PR is open for review. I marked this as a Draft because of this other PR https://github.com/ros2/rcl_logging/pull/36

**Comment by clalancette** [comment]
Is this one still viable, or do we have what we need from other PRs?

**Comment by clalancette** [comment]
I'm going to go ahead and close this one out for now.  Please feel free to reopen when we come back to addressing these tests.

**Pull request closed without merging**
